### ISSUE TITLE
"Repository structure for main is not compliant" error on install

### ISSUE THREAD

**Issue by davidn** [davidn/uvindex-hourly#1]
Reported at https://community.home-assistant.io/t/custom-component-epa-uv-index/564445/10. I removed and reinstalled the plugin but could not reproduce. Further investigation needed.

**Comment by coatmaker618** [comment]
Just adding some additional details here & a picture of the reported issue:

Home Assistant version info:

Core 2024.7.1
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240705.0

![image](https://github.com/davidn/uvindex-hourly/assets/45666704/7f12ccf7-716e-41db-959c-d60b4fbd0ed9)

Let me know what other info would help.

**Comment by davidn** [comment]
Thanks! I see the issue happens when adding the custom repo (as an integration). The reason for the issue is that (like other lovelace cards in HACS) this must be installed as Category "Plugin", not "Integration". It is confusing that HACS calls lovelace cards "plugins" I admit!

I will add install instructions to the README, I think that will go a long way to preventing people hitting this issue in the future.

**Comment by coatmaker618** [comment]
Well, that definitely isn't helping if it's supposed to be a plugin instead of an Integration.  I appreciate you adding that to the documentation.  Just a FYI, mine is labeled "Lovelace" not "Integration". Could be confusing for new people.

![image](https://github.com/davidn/uvindex-hourly/assets/45666704/a4b967f0-e430-4e34-a186-b769b615ad61)

**Comment by davidn** [comment]
Thanks. That is a lot less confusing than "plugin". I have updated the README to reflect this.
